### ISSUE TITLE
Allow filtering by port

### ISSUE THREAD

**Issue by jadolg** [swordfest/shadowmere#4]
There was a request to allow this in the main repo https://github.com/jadolg/shadowmere/issues/38
The backend part is done and live.
You can get all ports for active proxies with `/api/ports`
And filter using the port argument with `/api/proxies/?is_active=true&port=443`

**Comment by swordfest** [comment]
@jadolg this task has been solved already and it's ready for deployment. Although this solution is effective and works properly, it will require an update in the near future due to a misbehavior on the select component expand interaction.
